### ISSUE TITLE
Consistent taxon labels between treemachine and taxomachine

### ISSUE THREAD

**Issue by chinchliff** [OpenTreeOfLife/treemachine#131]
Taxon labels should have equivalent formatting options between these two repos. I have added some options to the taxomachine subtree method for label formatting. Would be good for them to be mirrored in treemachine. See https://github.com/OpenTreeOfLife/taxomachine/issues/74.

See the following taxomachine code for a reference to the options.
https://github.com/OpenTreeOfLife/taxomachine/blob/taxon_labels/src/main/java/org/opentree/taxonomy/plugins/taxonomy.java#L79

As part of this, treemachine should be transitioned to use the ot-base/.../GeneralUtils.java class and the treemachine version of this class should be retired.

**Comment by josephwb** [comment]
Do we know if this is satisfied?

**Comment by jar398** [comment]
I don't know. I would have to read the source code. The way to guarantee it would be for both services are using the same code for label generation. Personally I don't consider this very important, but will put it on my to-do list.

**Comment by josephwb** [comment]
treemachine uses the ot-base function `newickName`. So, easy to use in taxomachine (if not already).
I think this is pretty important. As far back as the hackathon people complained about inconsistent names.

**Comment by jar398** [comment]
If it's in ot-base the fix should be pretty easy. I'll assume the
treemachine part is done and that taxomachine has to be checked, which I
can do. Probably easier to just leave this issue open even though you could
argue it's in the wrong repo.

**Comment by jar398** [comment]
I've read through the code and it looks like both call GeneralUtils.newickName for name quoting, but the logic is different. treemachine GraphExplorer.getNodeLabel seems to have the right logic (the treatment of quotes), while taxomachine Taxonomy.getNodeLabel looks wrong.

I believe this is therefore not a treemachine issue at all, but rather a taxomachine issue, and taxomachine should be changed to be more like treemachine.

**Comment by josephwb** [comment]
thanks for tracking this down.

**Comment by jar398** [comment]
I spoke too soon. There seem to be at least two distinct problems. Here's what we have currently, for one example:

* treemachine: `'SAR324_clade_Marine_group_B_ott5247929'`
* taxomachine: `'SAR324 clade(Marine group B)'_ott5247929`

Taxomachine seems pretty clearly wrong in putting the `'` before the OTT id and not after, so I have fixed that. (But I don't know newick syntax, and maybe ' in the middle of a label is OK?)

However, the parentheses remain an issue, and I might need @josephwb's help with diagnosis. Somehow treemachine is stripping off the parentheses when it shouldn't be. The escaping is done by ot-base GeneralUtils.newickName in both systems, and the escaping logic isn't responsible, as far as I can tell from reading it. The parens must be lost before newickName gets called. The name comes from the "name" property of the neo4j node, which seems to be set from the taxonomy in IngestSynthesisData.  That ought to be correct, but it's not what I'm seeing.

The taxonomy has this:
    5247929	|	109210	|	SAR324 clade(Marine group B)	|	no rank	|	silva:U65908/#4	|		|		|	

Here are the curl commands:

    curl -X POST https://devapi.opentreeoflife.org/v3/tree_of_life/subtree -H "content-type:application/json" -d '{"ott_id":5247929}'
    curl -X POST https://devapi.opentreeoflife.org/v3/taxonomy/subtree -H "content-type:application/json" -d '{"ott_id":5247929}'

**Comment by mtholder** [comment]
see also https://github.com/OpenTreeOfLife/treemachine/issues/147

**Comment by jar398** [comment]
Thanks for the reference, I had forgotten about that discussion. I would like to do as you say and not convert space to underscore. Now would be the time to do it, with the v3 switchover. If we don't do it now, it may have to wait to v4. I can imagine the change breaking some clients.

The shared code:
https://github.com/OpenTreeOfLife/ot-base/blob/master/src/main/java/org/opentree/utils/GeneralUtils.java#L114

I would like to replace NEWICK_ILLEGAL_CHARS with NEWICK_LEGAL_CHARS, which would be ASCII letters and digits and maybe underscore. We are looking for a least common denominator among all Newick clients, right? 

This would mean all binomials would be quoted. If underscore is not treated as not needing quotation, then all labels would be quoted for name_and_id format.

**Comment by josephwb** [comment]
`newickName` is definitely doing replacing that it should not be. This is an easy fix, if we just decide on whether to:

1. always quote
2. quote only when illegal characters other than ' ' are present

It is standard practice that if labels contain only ' ' as illegal characters, then these are replaced by '_' and the label is not quoted. This is not aesthetically pleasing, but it is what is typically done.

But I bow to @mtholder's authority on what the appropriate thing to do is.

If we do go the "always quote" route, how should we handle `name_and_id` labels? We have always done:

    name + "_ottXXX" -> name_ottXXX

Should we now do the following?

    name + "_ottXXX" -> 'name ottXXX'

**Comment by jar398** [comment]
This is certainly a mess.  Can we agree that invertibility is a goal, and
recognize that we have names that contain both spaces and underscores, so
we cannot fold space and underscore to the same character in any context.
I think we should be able to agree that for format="name":

Aa -> Aa  no quoting needed.
Aa bb -> Aa_bb   by convention.
Aa_cc -> 'Aa_cc'   quoting needed because otherwise _ will become space on
inversion.
Aa cc_dd -> 'Aa cc_dd'   quoting needed because of _, similarly.

For format="name_and_id", we append 'ott123' before converting name form to
label form. If the name/id separator is _, then we have to quote
everything, as you say:

Aa -> Aa_ott122 -> 'Aa_ott122'     because otherwise the _ becomes a space
when unquoted.
Aa bb -> Aa bb_ott123 -> 'Aa bb_ott123'
Aa_cc -> Aa_cc_ott124 -> 'Aa_cc_ott124'
Aa cc_dd -> Aa cc_dd_ott125  ->  'Aa cc_dd_ott125'

If the separator (when in name form) is space instead of _, there is no
quoting in the common cases. If there's no reason to quote, the space
separator in the name form turns into an underscore in label form, and
turns back on ingest. But if quoting is needed it remains a space in label
form:

Aa -> Aa ott122 -> Aa_ott122     space as separator turns into _ - this is
a very common case
Aa bb -> Aa bb ott123 -> Aa_bb_ott123   ok - also a very common case
Aa_cc -> Aa_cc ott124 -> 'Aa_cc ott124'   otherwise the _ would be turned
into space
Aa cc_dd -> Aa cc_dd ott125  ->  'Aa cc_dd ott125' quoting needed because
of space.

The weird thing then with space as a name form separator is that the
separator when in label form looks different depending on whether you're
inside or outside the quotes. That's kind of ugly.  A workaround would be
to allow *either* space or _ as a separator in name form, with underscore
always in the newick. That would be not only ugly but a pain to implement.

The separator could be just about any non-letter character at all, given
that the syntactic constraints on the 'ott123' part remove any ambiguity,
but if it's anything other than space, then name_and_id labels will always
have to be quoted.

I think I will probably also defer to what @mtholder advises.

**Comment by josephwb** [comment]
This all sounds good.

**Comment by jar398** [comment]
Right now I favor space as separator.  Take name, append ' ottNNN', check
for presence of characters outside the safe set (which is at minimum
alphanumeric and space), then either quote or change spaces to _,
accordingly.

This keeps 99% of labels looking the way they currently do. People who want
to pull out the OTT id can still use a pretty simple regular expression
(look for ott[0-9]+'?$), without fully unquoting the label or caring which
separator occurs in the label.

**Comment by jar398** [comment]
treemachine has its own JadeNode class which has 

    ret.append(this.name.replaceAll(this.offendingChars,"_"));

which is not so good. 

treemachine GraphExporter has src/main/java/opentree/GraphExporter.java has all sorts of code to convert characters to underscore (although maybe we don't use this any more?).

taxomachine uses JadeNode from the 'jade' repo, which does not do any replaceAll, it just copies the name as it occurs in the jade tree into the newick string (the name was already quoted when the jade tree was created, as in treemachine).

So the difference between the two versions of JadeNode is the source of the inconsistency as regards the parentheses, and taxomachine's appending the ott id after quoting instead of before is the other source of inconsistency.

**Comment by josephwb** [comment]
GraphExporter is not used anymore. Having that deprecated JadeNode class is annoying and should change, although maybe hold off on replacing it since we are up against the clock? Seems instead we should just patch it in place now and replace later.

**Comment by jar398** [comment]
agreed on all counts.​

**Comment by josephwb** [comment]
Ok. I see that you assigned yourself to this, and I see you are familiar with all the code, so should I assume you will fix this, or I?

**Comment by jar398** [comment]
I fixed both taxomachine and treemachine (in the v3 branches); both now yield 'SAR324 clade(Marine group B)_ott5247929' for the example given above. As far as I know we now have consistency.

The question of invertibility is separate and maybe it should be its own issue. To get invertibility, we would have to treat _ as a character that needs to be quoted (since otherwise both space and _ would go to _). Currently it's treated as non-special. At that point the other analysis applies: either we have Foo_ott123 and 'Foo+ ott123', or we have 'Foo_ott123' and 'Foo+_ott123'. I have not yet done anything about this.

The question of retiring the deprecated jade classes is yet another separate issue.
