### ISSUE TITLE
edges corresponding to trivial phylogenetic statements considered conflict

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#158]
This was discussed on https://github.com/OpenTreeOfLife/treemachine/issues/157 along with another issue.

Just noting that I created an example branch https://github.com/OpenTreeOfLife/treemachine/tree/issue-158

The test script is `run-trivialconf-prob.sh`

**Comment by mtholder** [comment]
For the benefit of those who don't want to run the example. The inputs (in ranked order) are:

    tree1 (A,B)
    tree2 ((A,E),B)
    taxonomy (A,B,E)

The tree that is a perfect summary of all 3 trees is tree2 `((A,E),B)`

The TAG creates 2 internal nodes: `n1` is the root, `n7` is the MRCA of `A` and `B`.

The synthesis chooses the edge `rel11` attaching `A` to the root, because that is in the highest ranked tree. Then it rejects the edge `rel19` (which connects the MRCA of `A` and `E`) because its descendants overlap with `rel11`.

**Comment by mtholder** [comment]
I think that a viable solution would be to (in pseudocode):

    incoming_edges = find_incoming_TAG_edges(node)
    incoming_edges.sort(criterion=highest_ranked_trees_first)
    accepted = []
    for edge in incoming_edges:
        if count_descendant_tips(edge) > 1:
              if conflicts_with_accepted(edge, accepted):
                   log_rejection_of_edge(edge)
              else:
                   accepted.append(edge)
    # now add the trivial edges (if they didn't come in from a lower ranked tree)
    for edge in incoming_edges:
        if count_descendant_tips(edge) == 1:
              if conflicts_with_accepted(edge, accepted):
                   accepted.append(edge)

**Comment by blackrim** [comment]
Yes,  we have a branch and bound synth that solves this but doesn't scale
for the whole tol and didn't follow the use case of most of the trees
added.  However I am not sure if that method made it into the newer modular
bit that Cody constructed after the paper. I will check and can demo when I
find it

On Feb 1, 2015 4:24 AM, "Mark T. Holder" <notifications@github.com> wrote:
>
> For the benefit of those who don't want to run the example. The inputs
(in ranked order) are:
>
> tree1 (A,B)
> tree2 ((A,E),B)
> taxonomy (A,B,E)
>
> The tree that is a perfect summary of all 3 trees is tree2 ((A,E),B)
>
> The TAG creates 2 internal nodes: n1 is the root, n7 is the MRCA of A and
B.
>
> The synthesis chooses the edge rel11 attaching A to the root, because
that is in the highest ranked tree. Then it rejects the edge rel19 (which
connects the MRCA of A and E) because its descendants overlap with rel11.

**Comment by chinchliff** [comment]
I think it's in there but I don't know if it's functional. We weren't using
it at that point so I wasn't testing it as things were changed around it.
The code is still in there though.

**Comment by blackrim** [comment]
Yeah, I played around with it some and it seems like it doesn't work any
more (the underlying code sure works but it is looking at the wrong
information and needs to be updated). I can check on that.

**Comment by mtholder** [comment]
The pseudocode I wrote is implemented in https://github.com/OpenTreeOfLife/treemachine/commit/54fcad1e2bd72d20986f586cbab14d8e04832165 and this fixes this particular issue. 

I have not checked for ugly side effects of this change, though. 
Note: in that commit RankNontrivialNodeDesResolutionMethod.java is identical (other than in name) to RankNodeDesResolutionMethod.java.
The logic for checking for nontrivial cases was added to SynthesisExpander.java

I think that more test cases will reveal more complexity, and we'll need the RankNontrivialNodeDesResolutionMethod class to be fancier than NodeDesResolutionMethod

**Comment by chinchliff** [comment]
The 'trivialconf' test is now passing. I should have mentioned on #159 and #160 as well that the code for the new synth method that appears to resolve these issues is on the https://github.com/OpenTreeOfLife/treemachine/tree/rootward-synth branch. If you want to run it you'll also need to pull/recompile/install the 'new-synth-update' branches from ot-base and jade.

Here is an image of the tag and the output from this test. Again, as for #159 and #160, these results are obtained using node count/resolution as the optimality criterion for synthesis rather than tree rank. Please confirm and close if this issue seems solved.

```bash

FAILING_TREEMACHINE_TEST=trivialconf ./run_synth_tests.sh

# [snipped]

((A,E),B);
clade extracted: A, B, E
clade extracted: A, E
((E_ottE,A_ottA),B_ottB)life_ott805080;
clade extracted: A, B, E
clade extracted: A, E
SUCCESS! recovered expected tree.
Failed 0 out of 1 tests(s).
```

![image](https://cloud.githubusercontent.com/assets/1258397/6321784/9ad34bd6-bad3-11e4-9e80-b211a6db399e.png)

**Comment by mtholder** [comment]
looks good. I have a slight preference for keeping the issues open until we complete the synthesis changes (e.g. we still need to use the ranks, right?) and merge that into master. But you can certainly close the issues if you like. We can reopen them if we need to.

**Comment by chinchliff** [comment]
No, that seems fine. There are still related issues that might end up here.
Yes, still working on ranking.

Now we are working on improving speed/efficiency and reducing redundant
node creation. The method seems to find the appropriate nodes but it tends
to create a lot of nodes, some of which are probably not necessary for
assessing tree overlap.
