### ISSUE TITLE
Have option to return trees without extinct taxa

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/treemachine#186]
Suggested by @hyanwong in the email thread (don't know how to link to that).

The idea is that this would be an optional argument to treemachine services.

Bit of a moot point at the moment, as the current tree is not _supposed_ to contain any extinct taxa.

Would need: 1) a better taxonomy with some sort of "extinct" flag (probably already exists?), and 2) treemachine code to skip extinct taxa when extracting the tree. 

Should also have 2 versions of the full [newick](http://files.opentreeoflife.org/trees/) made available.

**Comment by mtholder** [comment]
https://groups.google.com/d/msg/opentreeoflife/Ix4Khm5c66c/JeL7I06KY8sJ

**Comment by jar398** [comment]
There is an extinct flag and it is set on 220,009 nodes in the taxonomy
(about 7%).  (Getting this information was the prime motivation for
importing IRMNG.) Treemachine excludes all of these taxa. The reason for
exclusion is that so many of them come (mostly from GBIF) and are not
placed correctly in NCBI or Index Fungorum.

But there are tons of false positives and false negatives. The false
positives make it look as if we need an option for excluding extinct taxa
from synthesis, when what's really going on is that we're missing the
information that they're extinct. The false negatives (probably not so many
of these) similarly make it look like we need an option for including them.

We are also missing lots of extinct taxa. When those are missing it looks
as if we need an option to include then, when actually they aren't in the
taxonomy in the first place. We've been talking about importing other
sources that can fill out the set.

Jonathan

**Comment by josephwb** [comment]
FWIW, this version loads without treemachine exploding, so that is good.
```
java -jar target/treemachine-0.0.1-SNAPSHOT-jar-with-dependencies.jar loadott <path_to_ott_folder>
```

**Comment by jar398** [comment]
'this version' = ?

**Comment by josephwb** [comment]
2.9draft7

**Comment by jar398** [comment]
Not sure what to do with this one. If we _know_ a taxon is extinct, it is marked that way, and excluded from synthesis. That constitutes part of a solution, but this feature was in place when this issue was first filed. That means this issue is about taxa that we know about but _don't_ know are extinct. There is no technical fix to that problem; we just have to harvest more knowledge.

If the request is to get a synthetic tree that *does* include extinct taxa, then please file an issue on one of the new synthesis method repos (I really don't know which, it would be either peyotl, otcetera, peyotl, or propinquity).

I think the following related issues cover the bases, so I'm going to close this one, but feel free to reopen if there's more to say that doesn't go anyplace else.

https://github.com/OpenTreeOfLife/reference-taxonomy/issues/176
https://github.com/OpenTreeOfLife/peyotl/issues/151
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/206

**Comment by hyanwong** [comment]
I can't remember the email thread, but I suspect that it was a request for 2 trees, (a) the current one, and (b) one with extract taxa also present. I don't need (b) at the moment, but perhaps others do. I think one of the points was to have a standard, easily parsable way to flag up extinct taxa in newick (b) without having to look in taxonomy.tsv. My suggestion was to use a plus sign, like the cross for extinct data, e.g. (XXX_ott1234+). But I'm sure there are better alternatives.

**Comment by jar398** [comment]
Doing this would require two different synthesis runs and two different
trees; annotating a single tree won't work because the presence of the
extinct taxa could change the topology.

As I say this should be filed with either peyotl, otcetera, or propinquity.
(if it isn't filed it will be forgotten about.)

**Comment by mtholder** [comment]
"Doing this would require two different synthesis runs and two different
trees" I suspect that we'd want to just prune the fossils from the full tree (once we produce a tree that has fossil taxa on it). 
So, while we *could* do separate runs and produce different summary trees (and @jar398  is certainly correct that the inclusion could affect the topology for the extant taxa), I suspect that we would want this sort of filtering option in tm-lite web services.
