### ISSUE TITLE
treemachine plugin versions

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/treemachine#208]
There has been some discussion on gitter about treemachine (tm-lite) plugin versions.

Plugin versioning has, to my knowledge, _never_ resided with treemachine. Plugin classes are named `tree_of_life` (synthetic tree queries), `GoLS` (webapp, mostly arguson via `getSyntheticTree`), and the deprecated `graph`. Serving locally I can do curl calls to these services using:
```
http://localhost:7474/db/data/ext/tree_of_life/graphdb/some_service_name
```
and
```
http://localhost:7474/db/data/ext/GoLS/graphdb/some_service_name`
```
On production/dev/test servers there must be some mechanism to map/redirect/whatever `GoLS` services to:
```
https://api.opentreeoflife.org/treemachine/v1/some_service_name
```
and `tree_of_life` services to:
```
https://api.opentreeoflife.org/v2/tree_of_life/some_service_name
```
`GoLS` services have _always_ been directed to "v1"; possibly this is not commonly known because it is unadvertized (@jimallman is the only user of those services that I am aware of) and it has only rarely got updated.

If people do not want `GoLS` services (again, primarily `getSyntheticTree`) to appear under "v1", then it needs to be changed outside of the treemachine code.

@jar398 recently asked me to rename the `tree_of_life` class to `tree_of_life_v3`. On the test server calls to:
```
https://test.opentreeoflife.org/v3/tree_of_life/some_service_name
```
use the renamed class, so obviously some mapping/redirection/whatever occurs from `v3/tree_of_life` -> `tree_of_life_v3`. Indeed, on my local machine I must call:
```
http://localhost:7474/db/data/ext/tree_of_life_v3/graphdb/some_service_name
```
to access these same services. I would think it is obvious why `v2/tree_of_life` no longer hits anything: the class `tree_of_life` was renamed, so no longer exists, so doesn't generate a plugin.

**Comment by jar398** [comment]
Naming and semantics are different issues.  The same methods are called by different names in Java/Neo4j and in apache. There's nothing contradictory about that. Method identity comes from semantics. We can talk about the naming independently of semantics.

There are v2 methods and v3 methods.  For apache these are known as v2/tree_of_life/* and v3/tree_of_life/*.  For java these are called tree_of_life/* and tree_of_life_v3/*.  If you want to see how apache maps URLs, the configuration is in germinator/deploy/setup/opentree-shared.conf.

For taxomachine, the v2 and v3 methods coexist within the same neo4j server, and the server is fully compatible with both v2 and v3 clients. No v2 client has to change, and v3 clients can take advantage of the v3 API.

The v2 and v3 methods *could* all be supported at the same time by a single treemachine neo4j server, as I described in another issue and as I did for taxomachine, but this idea was nixed.  As a result, we now have two servers that support the v2 methods but not v3 (api and devapi), and one server that supports draft v3 methods but not v2, and we will have to have a flag day when we swap v2 out and swap v3 in on production. I really hate working in this way, and if there were enough time I would just go and implement the v2 API in tm-lite myself, so we would not have to have a flag day.

Once the decision was made not to support v2, deleting the v2 plugin was forced.

Making incompatible changes to a method (such as changing integers to strings) without changing its URL is out of the question.

I'm not sure what you want me to do, or what you are asking. I do not see any issue or problem here. Can I close this issue?

**Comment by jar398** [comment]
(updated detail in previous comment: adding v2 to tm-lite would not be practical at this point, although we could have done it had we planned for it long ago. Instead I would have added v3 compatibility on top of treemachine in order to get v2/v3 coexistence. obviously as the propinquity-based tree gets closer the value of this proposition decreases.)

**Comment by josephwb** [comment]
I created this issue because of confusion over what exactly "v1" was, and statements like "i have no idea what happened to v2/X". You control all of this, but most of these statements were directed at or involved me.
If you want _both_ v2 and v3, you should have asked me to create a _new_ tree_of_life_v3 class rather than rename it (which effectively deletes v2).

**Comment by josephwb** [comment]
It is relatively straightforward to drop in a "new" tree_of_life class for the v2 services.

**Comment by jar398** [comment]
We cannot support the v2 services without implementing integer node ids,
and that idea was voted down (#200). It would certainly be easy to put code
behind the v2 URLs, but it would not be 'the v2 services' because it would
not support v2 semantics (i.e. integer node ids). Any behavior behind the
/v2/ URLs MUST be compatible with current clients. If it can't be made so,
the method must be deleted. That's what API versioning is about and why I
asked you to delete them from tm-lite.

I had thought about directing the v2 URLs to an older version of
treemachine, but I think that would be way too confusing, since the v2 and
v3 services would then operate on different trees.

Here is (more of) what I did wrong:
- I failed to adequately communicate that public v1 and v2 would be missing
from the test server (there's a name for this kind of bias, where something
is so obvious to you that it doesn't occur to you to say it, but it's not
obvious to others).
- I failed to be clear about what would happen to the private v1 GoLS
methods (like getSyntheticTree), which I assumed (correctly, I think) you
would update in place (which is OK only because it's private).  We have
evidence that they work, because the tree can be displayed, so is there
some other problem with the GoLS methods? Anything you didn't update can be
replaced with a v3 method, yes? (I haven't checked by Jim said the only v1
or v2 method required was for arguson.) And I think that's what eventually
happened.

I apologize for these, and sorry if you got blamed for something that was
my fault. It was a crazy week and I never stepped back to make a plan.

I have not asked you to do anything on this issue.  As far as I can tell
everything is as it should be. (Well, maybe nonworking *public* v1 methods
(not arguson) should be disabled, but that doesn't seem very important.)
Are you asking me to do anything?
